[package]
name = "kernel"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libkernel = { path = "../libkernel/" }
log = { version = "*", default-features = false }
num_enum = { version = "*", default-features = false }
limine = { git = "https://github.com/limine-bootloader/limine-rs", features = ["requests-section"] }
bit_field = "*"
bitflags = "*"
spin = "*"
paste = "*"
acpi = { path = "../../../acpi/acpi/" }
aml = "*"
miniz_oxide = "*"
bytemuck = "*"
rustc-demangle = "*"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "*"
raw-cpuid = { path = "../../../rust-cpuid/" }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true