[package]
name = "kernel"
version = "0.0.0"
edition = "2021"

[dependencies.libcommon]
path = "../shared/libcommon/"
features = ["global_allocator"]
[dependencies.libarch]
path = "../shared/libarch/"
[dependencies]
log = { version = "*", default-features = false }
num_enum = { version = "*", default-features = false }
limine = { git = "https://github.com/limine-bootloader/limine-rs", features = ["requests-section"] }
bit_field = "*"
bitflags = "*"
spin = "*"
paste = "*"
# TODO perhaps don't use ACPI / DTB in the kernel, but abstract it in libarch/libcommon/libkernel?
acpi = { git = "https://github.com/semiviral/acpi" }
aml = "*"
miniz_oxide = "*"
bytemuck = "*"
rustc-demangle = "*"
uart_16550 = "*"
port-rs = { path = "../shared/port-rs/" }

[profile.dev]
opt-level = 1

[profile.release]
# Release optimizations are specified in the xtask `Builder`. Optimization can be controlled with `-o p/s/ps`