[package]
name = "kernel"
version = "0.0.0"
edition = "2021"

[dependencies.port-rs]
path = "../shared/port-rs/"
[dependencies.uart]
path = "../shared/uart/"
[dependencies.msr]
path = "../shared/msr/"
[dependencies.apic]
path = "../shared/apic/"
[dependencies.slab]
path = "../shared/slab/"
[dependencies.lzstd]
git = "https://github.com/linuiz-project/lzstd"
[dependencies.spin]
git = "https://github.com/linuiz-project/spin-rs"
[dependencies.lza]
git = "https://github.com/linuiz-project/lza"
default-features = false
[dependencies.try_alloc]
git = "https://github.com/linuiz-project/try_alloc"
[dependencies.acpi]
git = "https://github.com/semiviral/acpi"

[dependencies]
log = { version = "*", default-features = false }
num_enum = { version = "*", default-features = false }
miniz_oxide = { version = "*", default-features = false }
limine = { version = "*", features = ["requests-section"] }
bit_field = "*"
bitflags = "*"
paste = "*"
bytemuck = "*"
rustc-demangle = "*"

[target.'cfg(target_arch = "x86_64")'.dependencies]
pic_8259 = { path = "../shared/pic_8259/" }
raw-cpuid = "*"
x86_64 = "*"

[profile.dev]
opt-level = 1

[profile.release]
# Release optimizations are specified in the xtask `Builder`. Optimization can be controlled with `-o p/s/ps`