[package]
name = "slab"
version = "0.1.0"
edition = "2021"

[dependencies.spin]
git = "https://github.com/semiviral/spin-rs"
[dependencies]
try_alloc = { path = "../../../submodules/try_alloc/"}
log = "*"