[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies.lza]
git = "https://github.com/linuiz-project/lza"
[dependencies]
clap = { version = "*", features = ["derive"] }
walkdir = "*"
xshell = "*"
toml_edit = "*"

[profile.dev]
debug = false