[package]
name = "gsai"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libkernel = { path = "../libkernel", features = [ "global_allocator" ] }
log = { version = "*", default-features = false }
bit_field = "*"
bitflags = "*"
num_enum = { version = "*", default-features = false }
spin = "*"
paste = "*"

[[bin]]
name = "kernel"
path = "src/kernel.rs"

[profile.release]
opt-level = 3