[package]
name = "gsai"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
efi_boot = { path = "../efi_boot/" }
lazy_static = { version = "*", features = ["spin_no_std"] }
bit_field = "*"
bitflags = "*"
x86_64 = "*"
spin = "*"


[[bin]]
name = "kernel"
path = "src/kernel.rs"