[package]
name = "gsai"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
efi_boot = { path = "../efi_boot/" }
libkernel = { path = "../libkernel", features = [ "kernel_impls" ] }
log = { version = "*", default-features = false }
lazy_static = "*"
bitflags = "*"
spin = "*"


[[bin]]
name = "kernel"
path = "src/kernel.rs"