[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i686-unknown-linux-gnu"
# out-dir = "./build/"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-args=-m32"
    ]