[package]
name = "libcommon"
version = "0.0.1"
authors = ["semiviral"]
edition = "2021"

[dependencies]
spin = { path = "../../../submodules/spin-rs/" }
port-rs = { path = "../port-rs/" }
bit_field = "*"
bitflags = "*"
paste = "*"