[package]
name = "libkernel"
version = "0.1.0"
edition = "2021"

[dependencies.libarch]
path = "../libarch/"
[dependencies.libcommon]
path = "../libcommon/"
features = ["global_allocator"]
[dependencies]
spin = "*"